# Generated by Django 4.0.1 on 2022-01-18 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('ET', 'Ethereum'), ('BC', 'Bitcoin')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='purchase',
            name='successful',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
