# Generated by Django 4.0.1 on 2022-01-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FermentationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('co2_level', models.IntegerField()),
                ('temperature', models.IntegerField()),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
