# Generated by Django 4.0.2 on 2022-02-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fermentationlab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Humiditity',
            new_name='Humidity',
        ),
    ]
