# Generated by Django 4.0.2 on 2022-02-17 13:59

from django.db import migrations, models
import fermentationlab.models


class Migration(migrations.Migration):

    dependencies = [
        ('fermentationlab', '0002_rename_humiditity_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiCameraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to=fermentationlab.models.user_directory_path)),
            ],
        ),
    ]
