# Generated by Django 4.0.2 on 2022-02-17 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fermentationlab', '0003_picameraimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picameraimage',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='picameraimage',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
